version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
