
language: python

python:
  - 3.7

env:
  global:
  # transifex_token
  - secure: "EeI+rinfLXlfWuDzVUIksnRLTlrOY5kVpuK0JL+4UHkjRcetmOxGC+zmTYf2Gk1/PqybyxNdWygdgMeSnnDbNLiZIBfWvQfz6bzii38b/019hO+ue7aa+Y2uNOiT5y0Xo0LSRavBR+6U78eCn00m9zJJCn0VdrPcQ31oUWeMAFB5EMGtS3aek84z/5HaK7yz0YtHwxMR7TaYDzH6yd4UuU/8Bgq0REnsvxy0YAZb1+4MJW/sFrqoNTbtrQSGO06iTmTDvrnjBDMsNO/Sp1O+0KdKmftzTq15qDwErRUEpu/59/pjNtXYHThuS3x0hLArCi50QaZJS2/p+ekUXMn+WdHlHxJIdWQHQZbGQFM9RV1p/gsJTZcK5ofZk3LbGceh2jV7YIKhs1+6c4suXPdDmunEr8On21aZq6izfvmytW1Mr6uDZbVKhQeysQwZtzFXWNO93BlNKb40qzaNC7wZbRBRp3TmRV8yoo5XlugjlYfNkSa3yYv1J90EJtFEq0YL46QzxSR2Eu69EA7C5X6jqF/LNWBB0KVt6axnOdROJoEqY2iPEHStMJ44OHficHbGf50/rAGFrS4JZqRz9MMj0wWdvb1TwcYwtRf0tNsKaXWCoHSXi3pBaG7yDmde/rkQI1HYdi3qViqMXdnAlBkaW52ip20Ybkk3yDcPXGiCFtU="
  #  github_token
  - secure: "Rotw5IvMPKugnm+Ohvrt2RZNGZK2beQIg2IEfvVK+2f37QeySehs/JoekI7xMPdKtlp2TX9ZT3WY29y6E192GmarCsFjuCbJWZ0PFvOIJSb5zmjO1L3HSTbNMTCU8Kewiv0LODM9k/KoXraizOQYewnD52bjgO3BupfYcRtODuyQDYFThZ9a5S6cvEGr4iV34Uviwlm0rLvWrwncfsoKH/2WAzDdChXhNoawtJugF2OHhZcXm1gXdHPfhWiNIzpZVO01wdt4PPSOBj/cGCVXTaWN/yus8qoF3xaPzB85dsox2H34IBsllJCV+/AFjbpwJD6LZbD7tgLDknmj7ILTFG7/B/ddSuEycxcO9+C4njRVxZFxg9/Lu3No1iDA5tMpiFUbAbXPzZL013tXo4DTbth2EnaaDPtY0pwvq9yZX/Or7Z3EFsYGyKPnN3cOiT4UWrZ04fqTyeMtW7jBR+6vOKkM9rw0dJ1yAqQbNgFZ428ktB9oknHxAkKuBieXceaeC3jaT9NSOybzwvPWDh3J5OD0InsaaQF7mK8DA7F15YbrU46vEL5H5TTcz57w+TMbo/VsxVWR8rhTCR3DvzmgwAwqU0pU95m/Uj8QoZTLIaf+qCCeX/Vj0q1k/b2aWAKV7IJm3vWOPalk+TYo5FByp9RCCN8dSHcBBZfSxrALslA="

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - nose2 -v


