
language: python

python:
  - 3.7

env:
  global:
  # transifex_token
  - secure: "EeI+rinfLXlfWuDzVUIksnRLTlrOY5kVpuK0JL+4UHkjRcetmOxGC+zmTYf2Gk1/PqybyxNdWygdgMeSnnDbNLiZIBfWvQfz6bzii38b/019hO+ue7aa+Y2uNOiT5y0Xo0LSRavBR+6U78eCn00m9zJJCn0VdrPcQ31oUWeMAFB5EMGtS3aek84z/5HaK7yz0YtHwxMR7TaYDzH6yd4UuU/8Bgq0REnsvxy0YAZb1+4MJW/sFrqoNTbtrQSGO06iTmTDvrnjBDMsNO/Sp1O+0KdKmftzTq15qDwErRUEpu/59/pjNtXYHThuS3x0hLArCi50QaZJS2/p+ekUXMn+WdHlHxJIdWQHQZbGQFM9RV1p/gsJTZcK5ofZk3LbGceh2jV7YIKhs1+6c4suXPdDmunEr8On21aZq6izfvmytW1Mr6uDZbVKhQeysQwZtzFXWNO93BlNKb40qzaNC7wZbRBRp3TmRV8yoo5XlugjlYfNkSa3yYv1J90EJtFEq0YL46QzxSR2Eu69EA7C5X6jqF/LNWBB0KVt6axnOdROJoEqY2iPEHStMJ44OHficHbGf50/rAGFrS4JZqRz9MMj0wWdvb1TwcYwtRf0tNsKaXWCoHSXi3pBaG7yDmde/rkQI1HYdi3qViqMXdnAlBkaW52ip20Ybkk3yDcPXGiCFtU="
  # github_token
  - secure: "Rotw5IvMPKugnm+Ohvrt2RZNGZK2beQIg2IEfvVK+2f37QeySehs/JoekI7xMPdKtlp2TX9ZT3WY29y6E192GmarCsFjuCbJWZ0PFvOIJSb5zmjO1L3HSTbNMTCU8Kewiv0LODM9k/KoXraizOQYewnD52bjgO3BupfYcRtODuyQDYFThZ9a5S6cvEGr4iV34Uviwlm0rLvWrwncfsoKH/2WAzDdChXhNoawtJugF2OHhZcXm1gXdHPfhWiNIzpZVO01wdt4PPSOBj/cGCVXTaWN/yus8qoF3xaPzB85dsox2H34IBsllJCV+/AFjbpwJD6LZbD7tgLDknmj7ILTFG7/B/ddSuEycxcO9+C4njRVxZFxg9/Lu3No1iDA5tMpiFUbAbXPzZL013tXo4DTbth2EnaaDPtY0pwvq9yZX/Or7Z3EFsYGyKPnN3cOiT4UWrZ04fqTyeMtW7jBR+6vOKkM9rw0dJ1yAqQbNgFZ428ktB9oknHxAkKuBieXceaeC3jaT9NSOybzwvPWDh3J5OD0InsaaQF7mK8DA7F15YbrU46vEL5H5TTcz57w+TMbo/VsxVWR8rhTCR3DvzmgwAwqU0pU95m/Uj8QoZTLIaf+qCCeX/Vj0q1k/b2aWAKV7IJm3vWOPalk+TYo5FByp9RCCN8dSHcBBZfSxrALslA="

install:
  - pip install -r requirements.txt
  - sed -i "s/__VERSION__/${TRAVIS_TAG:-0.0.0}/g" setup.py
  - python setup.py install

script:
  - nose2 -v

deploy:
  on:
    tags: true
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  distributions: sdist
  user:
    secure: "K/wtvhISwCuhx0Za/Q8tSDcS49cM4y0lviaE+dg2OGOhTKv2ArCQSo8ATatKzJdIiiiBkvu0hZJVnSXNTOEhVBHfhFZAfGyaj5opMlhnCPlkStWkJQjMioqQw93aNL5YYsQNmyaGsv+HwCT4u14gTH/9UO+THbYKxd1Vl2uDP3fUodvIjduC+JxeWpIkMLPnqh0aTUWXVyvuvlUg1tdqf0H/vPIitaCAzVl1VQpSQWQ/8+xYP+lzZUs7UWaUdFCQC0sLsI19wY8WCzcugX/sb50Anm2uFC0GwRmTMTiV9neGC8tjv5dICJKs9KmciCngXLND1D/1vq+z2iCI4a2rlT7nUBDaDjEowIY2qsnxT1IvUTr4bgJNLl1m+ff6VDWkiMgWV/yO2XALG3JoEnbI6Zd9CaCUBvzi9a4/eDATAXi7RBWDHMY2Z+FjA49f4ud1GRw6OR8vBPCS1mDehdKPIzD+60HvYew+YwlkzauH7y9Zb0sy861+amo+q3RTkr4ek5sdgzUhxTdlPAf12d1EwDz7hcwRNXeFOghf/Qc9H8IDb6pWj/0itCr65v4nNw5Un1u0UEuBFQmHBJHvknYPYKpWWJXCquXln559Yh15YYqnfaZklqx4b135qWSuYCBIBw8lG1MV9tRg2yxsGcC+hTXRnSGkjPmQBPdtX5PWMfs="
  password:
    secure: "nHPAVzs/jB8symXaJJTtNOzyw275wo0MR6DcM+2OPM19An1wPORhl5l5aZlrJ8R/GJu4hUEqLP1ePYGNZmrKKw++hh+vKkp7YE6U90Ryyt7cb0CIebjo/o2zp61tslpGejqKux8tWXsSQPHJWhsQx6Mk9WfXPszt4d2CtIu+tqes7XxHeM8y0qgLhRJ+wg1kc6Jbl2MCqq+qjv/VUFOQYVJXqd6tqdssC3wjxRhbzBQd1YQph0qAxQTgeJ/pJ5KDadzuWluayntnjgiNCkvjsPcIMuUG+cA3SJmOWhoB5q2tIaDq2yOa937un1OcM0Pl5EC4UtT3bQcJpy0AH6nJpUB6aBwQvD8E9qfKoSAMnCIZOgLPc0z80GFSX29s+DmAQncj8h14r9y5LU1+r7enagD+IQm5jf1GyGKTT76bgpO9Y9DswsfSnfXmpM9nJ+fPASGCxOaKrjIFNNh8HObD0dMSSwcu3hRqSTf21DKHUBWyFfkSFZ/Te6ymI59EnUjes4P8rWq8637FXo33u6YEtPpkZd6LoBY81DQvpLuIg3o2d33GP7ZBj2DTabxEEQ2pse7RitiPwGirpWO7/OcbD4Xed5oyWVVnYC3TD/USTC19pCs36BSsMHKQQahYa+KVf0S8S9seG1aqcjbbyXjFxa0lHrcV5evSllCE9MGkKfk="





