os:
  - linux

language: python

services:
  - docker

branches:
  only:
    - master
    - dev

jobs:
  include:
    - stage: Run tests
      name: QGIS Desktop 3.4

      before_install:
        - docker pull qgis/qgis:release-3_4

      install:
        - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}/lizmap:/lizmap -e DISPLAY=:99 qgis/qgis:release-3_4
        - sleep 10
        - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh lizmap"

      script:
        - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh lizmap.qgis_plugin_tools.infrastructure.test_runner.test_package"

#    - stage: Deploy
#      if: branch = master
#      on:
#         tags=true
#      name: Create release, plugins.qgis.org
#
#      install:
#        - pip install qgis-plugin-ci
#
#      before_deploy:
#        - export RELEASE_TITLE="Release of $TRAVIS_TAG"
#
#      deploy:
#
#        - provider: releases
#          edge: true
#          file: .
#          name: ${RELEASE_TITLE}
#          api_key: ${GH_TOKEN}
#
#        - provider: script
#          script: qgis-plugin-ci release ${TRAVIS_TAG} --github-token ${GH_TOKEN} --osgeo-username ${OSGEO_USERNAME} --osgeo-password {OSGEO_PASSWORD} --create-plugin-repo
