# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_lizmap.ui'
#
# Created: Tue Mar  5 15:11:51 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_lizmap(object):
    def setupUi(self, lizmap):
        lizmap.setObjectName(_fromUtf8("lizmap"))
        lizmap.resize(903, 642)
        self.gridLayout_9 = QtGui.QGridLayout(lizmap)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btHelp = QtGui.QPushButton(lizmap)
        self.btHelp.setObjectName(_fromUtf8("btHelp"))
        self.gridLayout.addWidget(self.btHelp, 0, 0, 1, 1)
        self.btSave = QtGui.QPushButton(lizmap)
        self.btSave.setObjectName(_fromUtf8("btSave"))
        self.gridLayout.addWidget(self.btSave, 0, 2, 1, 1)
        self.buttonClose = QtGui.QDialogButtonBox(lizmap)
        self.buttonClose.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonClose.setObjectName(_fromUtf8("buttonClose"))
        self.gridLayout.addWidget(self.buttonClose, 1, 3, 1, 1)
        self.btSync = QtGui.QPushButton(lizmap)
        self.btSync.setEnabled(True)
        self.btSync.setObjectName(_fromUtf8("btSync"))
        self.gridLayout.addWidget(self.btSync, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(lizmap)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.treeLayer = QtGui.QTreeWidget(self.groupBox_8)
        self.treeLayer.setAlternatingRowColors(True)
        self.treeLayer.setColumnCount(1)
        self.treeLayer.setObjectName(_fromUtf8("treeLayer"))
        self.treeLayer.headerItem().setText(0, _fromUtf8("Name"))
        self.treeLayer.header().setDefaultSectionSize(50)
        self.treeLayer.header().setMinimumSectionSize(50)
        self.treeLayer.header().setStretchLastSection(True)
        self.gridLayout_15.addWidget(self.treeLayer, 0, 0, 1, 1)
        self.cbRootGroupsAsBlock = QtGui.QCheckBox(self.groupBox_8)
        self.cbRootGroupsAsBlock.setObjectName(_fromUtf8("cbRootGroupsAsBlock"))
        self.gridLayout_15.addWidget(self.cbRootGroupsAsBlock, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox_9)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.inLayerTitle = QtGui.QLineEdit(self.groupBox_9)
        self.inLayerTitle.setObjectName(_fromUtf8("inLayerTitle"))
        self.verticalLayout.addWidget(self.inLayerTitle)
        self.label_8 = QtGui.QLabel(self.groupBox_9)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.teLayerAbstract = QtGui.QTextEdit(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teLayerAbstract.sizePolicy().hasHeightForWidth())
        self.teLayerAbstract.setSizePolicy(sizePolicy)
        self.teLayerAbstract.setObjectName(_fromUtf8("teLayerAbstract"))
        self.verticalLayout.addWidget(self.teLayerAbstract)
        self.label_10 = QtGui.QLabel(self.groupBox_9)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.inLayerLink = QtGui.QLineEdit(self.groupBox_9)
        self.inLayerLink.setObjectName(_fromUtf8("inLayerLink"))
        self.verticalLayout.addWidget(self.inLayerLink)
        self.cbToggled = QtGui.QCheckBox(self.groupBox_9)
        self.cbToggled.setObjectName(_fromUtf8("cbToggled"))
        self.verticalLayout.addWidget(self.cbToggled)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cbPopup = QtGui.QCheckBox(self.groupBox_9)
        self.cbPopup.setObjectName(_fromUtf8("cbPopup"))
        self.horizontalLayout_7.addWidget(self.cbPopup)
        self.btConfigurePopup = QtGui.QPushButton(self.groupBox_9)
        self.btConfigurePopup.setObjectName(_fromUtf8("btConfigurePopup"))
        self.horizontalLayout_7.addWidget(self.btConfigurePopup)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.cbGroupAsLayer = QtGui.QCheckBox(self.groupBox_9)
        self.cbGroupAsLayer.setObjectName(_fromUtf8("cbGroupAsLayer"))
        self.verticalLayout.addWidget(self.cbGroupAsLayer)
        self.cbLayerIsBaseLayer = QtGui.QCheckBox(self.groupBox_9)
        self.cbLayerIsBaseLayer.setObjectName(_fromUtf8("cbLayerIsBaseLayer"))
        self.verticalLayout.addWidget(self.cbLayerIsBaseLayer)
        self.cbSingleTile = QtGui.QCheckBox(self.groupBox_9)
        self.cbSingleTile.setObjectName(_fromUtf8("cbSingleTile"))
        self.verticalLayout.addWidget(self.cbSingleTile)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_9)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.liImageFormat = QtGui.QComboBox(self.groupBox_9)
        self.liImageFormat.setObjectName(_fromUtf8("liImageFormat"))
        self.liImageFormat.addItem(_fromUtf8(""))
        self.liImageFormat.addItem(_fromUtf8(""))
        self.liImageFormat.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.liImageFormat)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.cbCached = QtGui.QCheckBox(self.groupBox_9)
        self.cbCached.setObjectName(_fromUtf8("cbCached"))
        self.verticalLayout.addWidget(self.cbCached)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.inCacheExpiration = QtGui.QSpinBox(self.groupBox_9)
        self.inCacheExpiration.setMaximum(2592000)
        self.inCacheExpiration.setObjectName(_fromUtf8("inCacheExpiration"))
        self.horizontalLayout_2.addWidget(self.inCacheExpiration)
        self.label_16 = QtGui.QLabel(self.groupBox_9)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_2.addWidget(self.label_16)
        self.inMetatileSize = QtGui.QLineEdit(self.groupBox_9)
        self.inMetatileSize.setObjectName(_fromUtf8("inMetatileSize"))
        self.horizontalLayout_2.addWidget(self.inMetatileSize)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem2, 5, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_22 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_22.addWidget(self.label_21, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_13.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_11 = QtGui.QLabel(self.groupBox_12)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        self.inGoogleKey = QtGui.QLineEdit(self.groupBox_12)
        self.inGoogleKey.setMaximumSize(QtCore.QSize(100, 16777215))
        self.inGoogleKey.setObjectName(_fromUtf8("inGoogleKey"))
        self.horizontalLayout_13.addWidget(self.inGoogleKey)
        self.cbGoogleStreets = QtGui.QCheckBox(self.groupBox_12)
        self.cbGoogleStreets.setObjectName(_fromUtf8("cbGoogleStreets"))
        self.horizontalLayout_13.addWidget(self.cbGoogleStreets)
        self.cbGoogleSatellite = QtGui.QCheckBox(self.groupBox_12)
        self.cbGoogleSatellite.setObjectName(_fromUtf8("cbGoogleSatellite"))
        self.horizontalLayout_13.addWidget(self.cbGoogleSatellite)
        self.cbGoogleHybrid = QtGui.QCheckBox(self.groupBox_12)
        self.cbGoogleHybrid.setObjectName(_fromUtf8("cbGoogleHybrid"))
        self.horizontalLayout_13.addWidget(self.cbGoogleHybrid)
        self.cbGoogleTerrain = QtGui.QCheckBox(self.groupBox_12)
        self.cbGoogleTerrain.setObjectName(_fromUtf8("cbGoogleTerrain"))
        self.horizontalLayout_13.addWidget(self.cbGoogleTerrain)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.gridLayout_13.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_12)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cbOsmMapnik = QtGui.QCheckBox(self.groupBox_11)
        self.cbOsmMapnik.setObjectName(_fromUtf8("cbOsmMapnik"))
        self.horizontalLayout_9.addWidget(self.cbOsmMapnik)
        self.cbOsmMapquest = QtGui.QCheckBox(self.groupBox_11)
        self.cbOsmMapquest.setObjectName(_fromUtf8("cbOsmMapquest"))
        self.horizontalLayout_9.addWidget(self.cbOsmMapquest)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.gridLayout_10.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_11)
        self.gridLayout_22.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_7, 8, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setStyleSheet(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_5.addWidget(self.label_15)
        self.inMapScales = QtGui.QLineEdit(self.groupBox_6)
        self.inMapScales.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inMapScales.setObjectName(_fromUtf8("inMapScales"))
        self.horizontalLayout_5.addWidget(self.inMapScales)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_11.addWidget(self.label_13)
        self.inMinScale = QtGui.QLineEdit(self.groupBox_6)
        self.inMinScale.setEnabled(False)
        self.inMinScale.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inMinScale.setMaxLength(10)
        self.inMinScale.setObjectName(_fromUtf8("inMinScale"))
        self.horizontalLayout_11.addWidget(self.inMinScale)
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setEnabled(False)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_11.addWidget(self.label_14)
        self.inMaxScale = QtGui.QLineEdit(self.groupBox_6)
        self.inMaxScale.setEnabled(False)
        self.inMaxScale.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inMaxScale.setMaxLength(10)
        self.inMaxScale.setObjectName(_fromUtf8("inMaxScale"))
        self.horizontalLayout_11.addWidget(self.inMaxScale)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_6)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_6, 6, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem6, 7, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.cbActivatePrint = QtGui.QCheckBox(self.groupBox_10)
        self.cbActivatePrint.setEnabled(True)
        self.cbActivatePrint.setObjectName(_fromUtf8("cbActivatePrint"))
        self.horizontalLayout_6.addWidget(self.cbActivatePrint)
        self.cbActivateMeasure = QtGui.QCheckBox(self.groupBox_10)
        self.cbActivateMeasure.setEnabled(True)
        self.cbActivateMeasure.setObjectName(_fromUtf8("cbActivateMeasure"))
        self.horizontalLayout_6.addWidget(self.cbActivateMeasure)
        self.cbActivateZoomHistory = QtGui.QCheckBox(self.groupBox_10)
        self.cbActivateZoomHistory.setEnabled(True)
        self.cbActivateZoomHistory.setObjectName(_fromUtf8("cbActivateZoomHistory"))
        self.horizontalLayout_6.addWidget(self.cbActivateZoomHistory)
        self.cbActivateGeolocation = QtGui.QCheckBox(self.groupBox_10)
        self.cbActivateGeolocation.setEnabled(True)
        self.cbActivateGeolocation.setObjectName(_fromUtf8("cbActivateGeolocation"))
        self.horizontalLayout_6.addWidget(self.cbActivateGeolocation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_19 = QtGui.QLabel(self.groupBox_10)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_14.addWidget(self.label_19)
        self.liExternalSearch = QtGui.QComboBox(self.groupBox_10)
        self.liExternalSearch.setObjectName(_fromUtf8("liExternalSearch"))
        self.liExternalSearch.addItem(_fromUtf8(""))
        self.liExternalSearch.setItemText(0, _fromUtf8(""))
        self.liExternalSearch.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.liExternalSearch)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.gridLayout_14.addWidget(self.groupBox_10, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 0, 0, 1, 1)
        self.twLocateByLayerList = QtGui.QTableWidget(self.groupBox)
        self.twLocateByLayerList.setObjectName(_fromUtf8("twLocateByLayerList"))
        self.twLocateByLayerList.setColumnCount(4)
        self.twLocateByLayerList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twLocateByLayerList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twLocateByLayerList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twLocateByLayerList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twLocateByLayerList.setHorizontalHeaderItem(3, item)
        self.twLocateByLayerList.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.twLocateByLayerList, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.liLocateByLayerLayers = QtGui.QComboBox(self.groupBox)
        self.liLocateByLayerLayers.setObjectName(_fromUtf8("liLocateByLayerLayers"))
        self.horizontalLayout_16.addWidget(self.liLocateByLayerLayers)
        self.liLocateByLayerFields = QtGui.QComboBox(self.groupBox)
        self.liLocateByLayerFields.setObjectName(_fromUtf8("liLocateByLayerFields"))
        self.horizontalLayout_16.addWidget(self.liLocateByLayerFields)
        self.cbLocateByLayerDisplayGeom = QtGui.QCheckBox(self.groupBox)
        self.cbLocateByLayerDisplayGeom.setObjectName(_fromUtf8("cbLocateByLayerDisplayGeom"))
        self.horizontalLayout_16.addWidget(self.cbLocateByLayerDisplayGeom)
        self.btLocateByLayerAdd = QtGui.QPushButton(self.groupBox)
        self.btLocateByLayerAdd.setObjectName(_fromUtf8("btLocateByLayerAdd"))
        self.horizontalLayout_16.addWidget(self.btLocateByLayerAdd)
        self.btLocateByLayerDel = QtGui.QPushButton(self.groupBox)
        self.btLocateByLayerDel.setObjectName(_fromUtf8("btLocateByLayerDel"))
        self.horizontalLayout_16.addWidget(self.btLocateByLayerDel)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_20.addWidget(self.label_30, 0, 0, 1, 1)
        self.cbAnnotationLayerIsActive = QtGui.QCheckBox(self.groupBox_2)
        self.cbAnnotationLayerIsActive.setObjectName(_fromUtf8("cbAnnotationLayerIsActive"))
        self.gridLayout_20.addWidget(self.cbAnnotationLayerIsActive, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_3.addWidget(self.label_31)
        self.liAnnotationPointLayer = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liAnnotationPointLayer.sizePolicy().hasHeightForWidth())
        self.liAnnotationPointLayer.setSizePolicy(sizePolicy)
        self.liAnnotationPointLayer.setObjectName(_fromUtf8("liAnnotationPointLayer"))
        self.horizontalLayout_3.addWidget(self.liAnnotationPointLayer)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_3.addWidget(self.label_32)
        self.liAnnotationLineLayer = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liAnnotationLineLayer.sizePolicy().hasHeightForWidth())
        self.liAnnotationLineLayer.setSizePolicy(sizePolicy)
        self.liAnnotationLineLayer.setObjectName(_fromUtf8("liAnnotationLineLayer"))
        self.horizontalLayout_3.addWidget(self.liAnnotationLineLayer)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_3.addWidget(self.label_33)
        self.liAnnotationPolygonLayer = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liAnnotationPolygonLayer.sizePolicy().hasHeightForWidth())
        self.liAnnotationPolygonLayer.setSizePolicy(sizePolicy)
        self.liAnnotationPolygonLayer.setObjectName(_fromUtf8("liAnnotationPolygonLayer"))
        self.horizontalLayout_3.addWidget(self.liAnnotationPolygonLayer)
        self.gridLayout_20.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_ftp = QtGui.QWidget()
        self.tab_ftp.setObjectName(_fromUtf8("tab_ftp"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_ftp)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_ftp)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.inHost = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inHost.sizePolicy().hasHeightForWidth())
        self.inHost.setSizePolicy(sizePolicy)
        self.inHost.setObjectName(_fromUtf8("inHost"))
        self.gridLayout_11.addWidget(self.inHost, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_11.addWidget(self.label_2, 0, 2, 1, 1)
        self.inPort = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inPort.sizePolicy().hasHeightForWidth())
        self.inPort.setSizePolicy(sizePolicy)
        self.inPort.setObjectName(_fromUtf8("inPort"))
        self.gridLayout_11.addWidget(self.inPort, 0, 3, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.inUsername = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inUsername.sizePolicy().hasHeightForWidth())
        self.inUsername.setSizePolicy(sizePolicy)
        self.inUsername.setObjectName(_fromUtf8("inUsername"))
        self.gridLayout_8.addWidget(self.inUsername, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 1, 0, 1, 1)
        self.inPassword = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inPassword.sizePolicy().hasHeightForWidth())
        self.inPassword.setSizePolicy(sizePolicy)
        self.inPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.inPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.inPassword.setObjectName(_fromUtf8("inPassword"))
        self.gridLayout_8.addWidget(self.inPassword, 1, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem11, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_ftp)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_12.addWidget(self.label_6, 0, 0, 1, 1)
        self.inRemotedir = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inRemotedir.sizePolicy().hasHeightForWidth())
        self.inRemotedir.setSizePolicy(sizePolicy)
        self.inRemotedir.setObjectName(_fromUtf8("inRemotedir"))
        self.gridLayout_12.addWidget(self.inRemotedir, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_12.addWidget(self.label_5, 1, 0, 1, 1)
        self.inLocaldir = QtGui.QLineEdit(self.groupBox_4)
        self.inLocaldir.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inLocaldir.sizePolicy().hasHeightForWidth())
        self.inLocaldir.setSizePolicy(sizePolicy)
        self.inLocaldir.setObjectName(_fromUtf8("inLocaldir"))
        self.gridLayout_12.addWidget(self.inLocaldir, 1, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_4, 2, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem12, 3, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_ftp)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbWinscpIn = QtGui.QLabel(self.groupBox_5)
        self.lbWinscpIn.setObjectName(_fromUtf8("lbWinscpIn"))
        self.horizontalLayout.addWidget(self.lbWinscpIn)
        self.inWinscpPath = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inWinscpPath.sizePolicy().hasHeightForWidth())
        self.inWinscpPath.setSizePolicy(sizePolicy)
        self.inWinscpPath.setObjectName(_fromUtf8("inWinscpPath"))
        self.horizontalLayout.addWidget(self.inWinscpPath)
        self.btWinscpPath = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btWinscpPath.sizePolicy().hasHeightForWidth())
        self.btWinscpPath.setSizePolicy(sizePolicy)
        self.btWinscpPath.setObjectName(_fromUtf8("btWinscpPath"))
        self.horizontalLayout.addWidget(self.btWinscpPath)
        self.gridLayout_19.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.lbWinscpHelp = QtGui.QLabel(self.groupBox_5)
        self.lbWinscpHelp.setObjectName(_fromUtf8("lbWinscpHelp"))
        self.gridLayout_19.addWidget(self.lbWinscpHelp, 1, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lbWinscpSession = QtGui.QLabel(self.groupBox_5)
        self.lbWinscpSession.setObjectName(_fromUtf8("lbWinscpSession"))
        self.gridLayout_7.addWidget(self.lbWinscpSession, 0, 0, 1, 1)
        self.inWinscpSession = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inWinscpSession.sizePolicy().hasHeightForWidth())
        self.inWinscpSession.setSizePolicy(sizePolicy)
        self.inWinscpSession.setObjectName(_fromUtf8("inWinscpSession"))
        self.gridLayout_7.addWidget(self.inWinscpSession, 0, 1, 1, 1)
        self.lbWinscpCriteria = QtGui.QLabel(self.groupBox_5)
        self.lbWinscpCriteria.setObjectName(_fromUtf8("lbWinscpCriteria"))
        self.gridLayout_7.addWidget(self.lbWinscpCriteria, 1, 0, 1, 1)
        self.inWinscpCriteria = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inWinscpCriteria.sizePolicy().hasHeightForWidth())
        self.inWinscpCriteria.setSizePolicy(sizePolicy)
        self.inWinscpCriteria.setObjectName(_fromUtf8("inWinscpCriteria"))
        self.gridLayout_7.addWidget(self.inWinscpCriteria, 1, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_7, 2, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_5, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_ftp, _fromUtf8(""))
        self.tab_main = QtGui.QWidget()
        self.tab_main.setObjectName(_fromUtf8("tab_main"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_main)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.outLog = QtGui.QTextEdit(self.tab_main)
        self.outLog.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.outLog.setReadOnly(True)
        self.outLog.setObjectName(_fromUtf8("outLog"))
        self.gridLayout_5.addWidget(self.outLog, 0, 0, 1, 5)
        self.btClearlog = QtGui.QPushButton(self.tab_main)
        self.btClearlog.setObjectName(_fromUtf8("btClearlog"))
        self.gridLayout_5.addWidget(self.btClearlog, 1, 0, 2, 1)
        self.btCancelFtpSync = QtGui.QPushButton(self.tab_main)
        self.btCancelFtpSync.setEnabled(True)
        self.btCancelFtpSync.setObjectName(_fromUtf8("btCancelFtpSync"))
        self.gridLayout_5.addWidget(self.btCancelFtpSync, 1, 4, 1, 1)
        self.outState = QtGui.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.outState.setFont(font)
        self.outState.setText(_fromUtf8(""))
        self.outState.setObjectName(_fromUtf8("outState"))
        self.gridLayout_5.addWidget(self.outState, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab_main, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(lizmap)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonClose, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), lizmap.close)
        QtCore.QMetaObject.connectSlotsByName(lizmap)
        lizmap.setTabOrder(self.tabWidget, self.treeLayer)
        lizmap.setTabOrder(self.treeLayer, self.inLayerTitle)
        lizmap.setTabOrder(self.inLayerTitle, self.teLayerAbstract)
        lizmap.setTabOrder(self.teLayerAbstract, self.inLayerLink)
        lizmap.setTabOrder(self.inLayerLink, self.cbToggled)
        lizmap.setTabOrder(self.cbToggled, self.cbPopup)
        lizmap.setTabOrder(self.cbPopup, self.btConfigurePopup)
        lizmap.setTabOrder(self.btConfigurePopup, self.cbGroupAsLayer)
        lizmap.setTabOrder(self.cbGroupAsLayer, self.cbLayerIsBaseLayer)
        lizmap.setTabOrder(self.cbLayerIsBaseLayer, self.cbSingleTile)
        lizmap.setTabOrder(self.cbSingleTile, self.liImageFormat)
        lizmap.setTabOrder(self.liImageFormat, self.cbCached)
        lizmap.setTabOrder(self.cbCached, self.inCacheExpiration)
        lizmap.setTabOrder(self.inCacheExpiration, self.inMetatileSize)
        lizmap.setTabOrder(self.inMetatileSize, self.inMinScale)
        lizmap.setTabOrder(self.inMinScale, self.inMaxScale)
        lizmap.setTabOrder(self.inMaxScale, self.inMapScales)
        lizmap.setTabOrder(self.inMapScales, self.cbOsmMapquest)
        lizmap.setTabOrder(self.cbOsmMapquest, self.inGoogleKey)
        lizmap.setTabOrder(self.inGoogleKey, self.cbGoogleStreets)
        lizmap.setTabOrder(self.cbGoogleStreets, self.cbGoogleSatellite)
        lizmap.setTabOrder(self.cbGoogleSatellite, self.cbGoogleHybrid)
        lizmap.setTabOrder(self.cbGoogleHybrid, self.cbGoogleTerrain)
        lizmap.setTabOrder(self.cbGoogleTerrain, self.inHost)
        lizmap.setTabOrder(self.inHost, self.inPort)
        lizmap.setTabOrder(self.inPort, self.inUsername)
        lizmap.setTabOrder(self.inUsername, self.inPassword)
        lizmap.setTabOrder(self.inPassword, self.inRemotedir)
        lizmap.setTabOrder(self.inRemotedir, self.inLocaldir)
        lizmap.setTabOrder(self.inLocaldir, self.inWinscpPath)
        lizmap.setTabOrder(self.inWinscpPath, self.btWinscpPath)
        lizmap.setTabOrder(self.btWinscpPath, self.inWinscpSession)
        lizmap.setTabOrder(self.inWinscpSession, self.inWinscpCriteria)
        lizmap.setTabOrder(self.inWinscpCriteria, self.outLog)
        lizmap.setTabOrder(self.outLog, self.btClearlog)
        lizmap.setTabOrder(self.btClearlog, self.buttonClose)
        lizmap.setTabOrder(self.buttonClose, self.btSync)
        lizmap.setTabOrder(self.btSync, self.btCancelFtpSync)
        lizmap.setTabOrder(self.btCancelFtpSync, self.btSave)

    def retranslateUi(self, lizmap):
        lizmap.setWindowTitle(QtGui.QApplication.translate("lizmap", "LizMap", None, QtGui.QApplication.UnicodeUTF8))
        self.btHelp.setText(QtGui.QApplication.translate("lizmap", "ui.main.btHelp", None, QtGui.QApplication.UnicodeUTF8))
        self.btSave.setText(QtGui.QApplication.translate("lizmap", "layers.btSave.label", None, QtGui.QApplication.UnicodeUTF8))
        self.btSync.setText(QtGui.QApplication.translate("lizmap", "layers.btSync.label", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("lizmap", "ui.groupBox.treeLayers", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRootGroupsAsBlock.setText(QtGui.QApplication.translate("lizmap", "layers.rootGroupsAsBlock", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("lizmap", "ui.groupBox.settingLayer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("lizmap", "layers.layer.title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("lizmap", "layers.layer.abstract", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("lizmap", "layers.layer.link", None, QtGui.QApplication.UnicodeUTF8))
        self.cbToggled.setText(QtGui.QApplication.translate("lizmap", "layers.layer.toggled", None, QtGui.QApplication.UnicodeUTF8))
        self.cbPopup.setText(QtGui.QApplication.translate("lizmap", "layers.layer.popup", None, QtGui.QApplication.UnicodeUTF8))
        self.btConfigurePopup.setText(QtGui.QApplication.translate("lizmap", "layers.popup.configure", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGroupAsLayer.setText(QtGui.QApplication.translate("lizmap", "layers.layer.groupAsLayer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbLayerIsBaseLayer.setText(QtGui.QApplication.translate("lizmap", "layers.layer.baselayer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSingleTile.setText(QtGui.QApplication.translate("lizmap", "layers.layer.singletile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("lizmap", "layers.imageFormat.label", None, QtGui.QApplication.UnicodeUTF8))
        self.liImageFormat.setItemText(0, QtGui.QApplication.translate("lizmap", "png", None, QtGui.QApplication.UnicodeUTF8))
        self.liImageFormat.setItemText(1, QtGui.QApplication.translate("lizmap", "png; mode=8bit", None, QtGui.QApplication.UnicodeUTF8))
        self.liImageFormat.setItemText(2, QtGui.QApplication.translate("lizmap", "jpeg", None, QtGui.QApplication.UnicodeUTF8))
        self.cbCached.setText(QtGui.QApplication.translate("lizmap", "layers.layer.cached", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("lizmap", "layers.layer.cacheExpiration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("lizmap", "layers.layer.metatileSize", None, QtGui.QApplication.UnicodeUTF8))
        self.inMetatileSize.setInputMask(QtGui.QApplication.translate("lizmap", "0,0;_", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("lizmap", "layers.label", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("lizmap", "map.public.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("lizmap", "map.public.help", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("lizmap", "map.google.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("lizmap", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGoogleStreets.setText(QtGui.QApplication.translate("lizmap", "Streets", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGoogleSatellite.setText(QtGui.QApplication.translate("lizmap", "Satellite", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGoogleHybrid.setText(QtGui.QApplication.translate("lizmap", "Hybrid", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGoogleTerrain.setText(QtGui.QApplication.translate("lizmap", "Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("lizmap", "map.openstreetmap.label", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOsmMapnik.setText(QtGui.QApplication.translate("lizmap", "OSM Mapnik", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOsmMapquest.setText(QtGui.QApplication.translate("lizmap", "OSM Mapquest", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("lizmap", "map.scales.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("lizmap", "map.mapScales.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("lizmap", "map.minScale.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("lizmap", "map.maxScale.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("lizmap", "map.scales.help", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("lizmap", "map.visibletools.label", None, QtGui.QApplication.UnicodeUTF8))
        self.cbActivatePrint.setText(QtGui.QApplication.translate("lizmap", "map.tool.print", None, QtGui.QApplication.UnicodeUTF8))
        self.cbActivateMeasure.setText(QtGui.QApplication.translate("lizmap", "map.tool.measure", None, QtGui.QApplication.UnicodeUTF8))
        self.cbActivateZoomHistory.setText(QtGui.QApplication.translate("lizmap", "map.tool.zoom.history", None, QtGui.QApplication.UnicodeUTF8))
        self.cbActivateGeolocation.setText(QtGui.QApplication.translate("lizmap", "map.tool.geolocation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("lizmap", "map.tool.externalSearch.label", None, QtGui.QApplication.UnicodeUTF8))
        self.liExternalSearch.setItemText(1, QtGui.QApplication.translate("lizmap", "nominatim", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("lizmap", "map.label", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("lizmap", "tools.locateByLayer.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("lizmap", "tools.locateByLayer.description", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLocateByLayerList.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("lizmap", "twLocateByLayer.col.layer", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLocateByLayerList.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("lizmap", "twLocateByLayer.col.field", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLocateByLayerList.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("lizmap", "twLocateByLayer.col.displayGeom", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLocateByLayerList.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("lizmap", "twLocateByLayer.col.id", None, QtGui.QApplication.UnicodeUTF8))
        self.cbLocateByLayerDisplayGeom.setText(QtGui.QApplication.translate("lizmap", "tools.locateByLayer.cbDisplayGeom", None, QtGui.QApplication.UnicodeUTF8))
        self.btLocateByLayerAdd.setText(QtGui.QApplication.translate("lizmap", "tools.btLocateByLayerAdd", None, QtGui.QApplication.UnicodeUTF8))
        self.btLocateByLayerDel.setText(QtGui.QApplication.translate("lizmap", "tools.btLocateByLayerDel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("lizmap", "tools.annotationLayer.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("lizmap", "tools.annotationLayer.description", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAnnotationLayerIsActive.setText(QtGui.QApplication.translate("lizmap", "tools.annotationLayer.cbAnnotationLayerIsActive", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("lizmap", "annotationPointLayer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("lizmap", "annotationLineLayer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("lizmap", "annotationPolygonLayer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("lizmap", "tools.label", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("lizmap", "ftp.title.parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("lizmap", "ftp.host.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("lizmap", "ftp.port.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("lizmap", "ftp.username.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("lizmap", "ftp.password.label", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("lizmap", "ftp.title.directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("lizmap", "ftp.remotedir.label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("lizmap", "ftp.localdir.label", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("lizmap", "ftp.title.winscp", None, QtGui.QApplication.UnicodeUTF8))
        self.lbWinscpIn.setText(QtGui.QApplication.translate("lizmap", "ftp.winscp.label", None, QtGui.QApplication.UnicodeUTF8))
        self.btWinscpPath.setText(QtGui.QApplication.translate("lizmap", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbWinscpHelp.setText(QtGui.QApplication.translate("lizmap", "ftp.winscp.help.label", None, QtGui.QApplication.UnicodeUTF8))
        self.lbWinscpSession.setText(QtGui.QApplication.translate("lizmap", "ftp.winscp.session", None, QtGui.QApplication.UnicodeUTF8))
        self.lbWinscpCriteria.setText(QtGui.QApplication.translate("lizmap", "ftp.winscp.criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ftp), QtGui.QApplication.translate("lizmap", "ftp.label", None, QtGui.QApplication.UnicodeUTF8))
        self.btClearlog.setText(QtGui.QApplication.translate("lizmap", "log.btClearLog.label", None, QtGui.QApplication.UnicodeUTF8))
        self.btCancelFtpSync.setText(QtGui.QApplication.translate("lizmap", "log.btCancelSync.label", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), QtGui.QApplication.translate("lizmap", "log.label", None, QtGui.QApplication.UnicodeUTF8))

