variables:
  FACTORY_PRODUCT_NAME: lizmap
  FACTORY_PACKAGE_NAME: lizmap_qgis_plugin
  FACTORY_PACKAGE_TYPE: plugin
  FACTORY_MANIFEST: ".lizcloud/factory.manifest"

build:infrav3:
  stage: build
  script:
    - make -C .lizcloud -f factory.mk package
  environment:
    name: snap
  artifacts:
    paths:
      - ".lizcloud/factory.manifest"
  only:
    refs:
      - tags
      - dev
  tags:
    - infrav3

deploy:infrav3:
  stage: deploy 🚀
  script:
    - $FACTORY_SCRIPTS/deploy-package $FACTORY_PACKAGE_NAME
  dependencies:
    - build:infrav3
  environment:
    name: snap
  only:
    refs:
      - tags
      - dev
  tags:
    - infrav3

release:infrav3:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-package $FACTORY_PACKAGE_NAME
  environment:
    name: production
  dependencies:
    - build:infrav3
  when: manual
  only:
    - tags
  tags:
    - infrav3

build:infrav2:
  stage: build
  script:
    - make -C .lizcloud -f fabric.mk package
  environment:
    name: snap
  only:
    refs:
      - tags
      - dev
  tags:
    - fabric

deploy:infrav2:
  stage: deploy 🚀
  script:
    - sudo -u fabric fab snap deploy:qgis310_lizmap,force=true
  dependencies:
    - build:infrav2
  environment:
    name: snap
  only:
    refs:
      - tags
      - dev
  tags:
    - fabric

release:infrav2:
  stage: release
  script:
    - sudo -u fabric fab prod release:qgis310_lizmap
  environment:
    name: production
  dependencies:
    - build:infrav2
  when: manual
  only:
    - tags
  tags:
    - fabric

tickets:
  stage: deploy 🚀
  when: manual
  only:
    - tags
  tags:
    - factory
  script:
    # Lizmap-box
    - >
      curl
      --header 'Content-Type:application/json'
      --header "PRIVATE-TOKEN:${USER_TOKEN}"
      --data '{
      "id":70,
      "assignee_ids":[77],
      "labels":"qgis server",
      "title":"Nouvelle version de Lizmap plugin QGIS Serveur : '"${CI_COMMIT_REF_NAME}"'",
      "description":"Il existe une nouvelle version de Lizmap plugin QGIS Serveur : '"${CI_COMMIT_REF_NAME}"' 👍\n Lien vers la pipeline https://projects.3liz.org/lizmap/lizmap-plugin/pipelines/'"${CI_PIPELINE_ID}"' \n"}'
      --request POST https://projects.3liz.org/api/v4/projects/70/issues
    # Infra-doc
    - >
      curl
      --header 'Content-Type:application/json'
      --header "PRIVATE-TOKEN:${USER_TOKEN}"
      --data '{
      "id":7,
      "assignee_ids":[2],
      "labels":"SAAS Qgis,release,infra-v2",
      "title":"Nouvelle version de Lizmap plugin QGIS Serveur : '"${CI_COMMIT_REF_NAME}"'",
      "description":"Il existe une nouvelle version de Lizmap plugin QGIS Serveur : '"${CI_COMMIT_REF_NAME}"' 👍\n Lien vers la pipeline https://projects.3liz.org/lizmap/lizmap-plugin/pipelines/'"${CI_PIPELINE_ID}"' \n"}'
      --request POST https://projects.3liz.org/api/v4/projects/7/issues
    - >
      curl
      --header 'Content-Type:application/json'
      --header "PRIVATE-TOKEN:${USER_TOKEN}"
      --data '{
      "id":7,
      "assignee_ids":[5],
      "labels":"SAAS Qgis,release,infra-v3",
      "title":"Nouvelle version de Lizmap plugin QGIS Serveur : '"${CI_COMMIT_REF_NAME}"'",
      "description":"Il existe une nouvelle version de Lizmap plugin QGIS Serveur : '"${CI_COMMIT_REF_NAME}"' 👍\n Lien vers la pipeline https://projects.3liz.org/lizmap/lizmap-plugin/pipelines/'"${CI_PIPELINE_ID}"' \n"}'
      --request POST https://projects.3liz.org/api/v4/projects/7/issues
