name: Flake8

on: [push, pull_request]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@master
      - name: PyCharm Python Security Scanner
        uses: tonybaloney/pycharm-security@1.20.1
