name: Server 🎳

on:
  push:
#    paths:
#      - '**.py'
  pull_request:
#    paths:
#      - '**.py'

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Create dir
        run: |
          mkdir .local
          mkdir .cache

      - name: Running tests
        run: >-
          docker run
          --rm
          --name qgis-server
          -u $(id -u)
          -v ${GITHUB_WORKSPACE}/.cache:/.cache
          -e PIP_CACHE_DIR=/.cache
          -w /src/test/server
          -e PYTEST_ADDOPTS=""
          -v ${GITHUB_WORKSPACE}:/src
          -v ${GITHUB_WORKSPACE}/.local:/.local
          3liz/qgis-platform:3.10
          ./run-tests.sh
