name: Transifex 🗺

on:
  push:
    branches:
      - master
#      - dev
    paths:
      - '**.py'
      - '**.ui'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == '3liz'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - uses: actions/cache@v3.0.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/packaging.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python requirements
      run: pip install -r requirements/packaging.txt

    - name: Push to Transifex
      run: qgis-plugin-ci push-translation ${{ secrets.TRANSIFEX_TOKEN }}
