name: Transifex 🗺

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.ui'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == '3liz'
    container: 3liz/qgis-plugin-ci:endeavour
    steps:

      - uses: actions/checkout@v5

      - name: Push to Transifex
        run: qgis-plugin-ci push-translation ${{ secrets.TRANSIFEX_TOKEN }}
