name: Transifex 🗺

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.ui'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == '3liz'
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          architecture: x64
          cache: "pip"
          cache-dependency-path: "requirements/packaging.txt"

      - name: Install Packaging CI
        run: |
            sudo apt-get -qq update
            sudo apt-get -qq install qttools5-dev-tools pyqt5-dev-tools
            pip install --quiet -r requirements/packaging.txt
 
      - name: Push to Transifex
        run: qgis-plugin-ci push-translation ${{ secrets.TRANSIFEX_TOKEN }}
