name: Transifex 🗺

on:
  push:
    branches:
      - master
#      - dev
    paths:
      - '**.py'
      - '**.ui'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == '3liz'
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/packaging.txt"

      - name: Install Python requirements
        run: pip install -r requirements/packaging.txt

      - name: Push to Transifex
        run: qgis-plugin-ci push-translation ${{ secrets.TRANSIFEX_TOKEN }}
